### PR TITLE
Update from upstream

### PR DESCRIPTION
**Pull request by dja**

### CODE REVIEW

**Review by logankeenan — APPROVED** [review]

**Comment by logankeenan** [comment]
@dja - want to merge this in?

**Comment by dja** [comment]
Up to you. I haven't taken a look at it.

**Comment by logankeenan** [comment]
@dja we're currently on the latest commit [5d601ac](https://github.com/ritual/account-manager-api/blob/main/Gemfile#L103) in our Gemfile for the Yotpo SDK, which aligns with the last commit in this PR.  I'd like to merge this before integrating our fork.

**Comment by logankeenan** [comment]
@dja - just a friendly reminder to merge this PR, thank you!

**Pull request merged**
